name: Test

on: pull_request

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bazelisk
        run: |
          curl -fsSL -o /usr/local/bin/bazel https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64
          chmod +x /usr/local/bin/bazel

      - name: Run tests and build
        run: bazel test //common:all //client:all && bazel build //client:site
